baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "Hugo Try"
theme = "mainroad"
pygmentsCodeFences = true

[params]
  author = "panorama"
  hololive_en = [
    "Gawr Gura",
    "Takanashi Kiara",
    "Mori Calliope",
    "Ninomae Ina'nis",
    "Watson Amelia"
  ]
